dbt_project:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 8123
      user: default
      password: clickhouse
      schema: thelook
      secure: false
      threads: 4
